version: 2
jobs:
  build:
    working_directory: ~/compiler

    docker:
      - image: jbw3/compiler:0.2.0

    steps:
      - checkout
      - run: mkdir release
      - run: cd release
      - run: cmake ../src -DLLVM_DIR=/usr/lib/llvm-10/cmake -DCMAKE_BUILD_TYPE=Release
      - run: make
      - run: make test
