version: 2
jobs:
  build:
    working_directory: ~/compiler

    docker:
      - image: jbw3/compiler:0.3.0

    steps:
      - checkout
      - run: |
          mkdir release
          cd release
          cmake ../src -DCMAKE_CXX_COMPILER=clang++-10 -DLLVM_DIR=/usr/lib/llvm-10/cmake -DCMAKE_BUILD_TYPE=Release
          make
          make test
