version: 2
jobs:
  build:
    working_directory: ~/compiler

    docker:
      - image: jbw3/compiler:0.5.0

    resource_class: small

    steps:
      - checkout
      - run: |
          mkdir release
          cd release
          cmake ../src -DCMAKE_CXX_COMPILER=clang++-12 -DLLVM_DIR=/usr/lib/llvm-12/cmake -DCMAKE_BUILD_TYPE=Release
          make
          make test
