version: 2
jobs:
  build:
    working_directory: ~/compiler

    docker:
      - image: jbw3/compiler:0.7.0

    resource_class: medium

    steps:
      - checkout:
          method: blobless
      - run: |
          mkdir release
          cd release
          cmake ../src -DCMAKE_CXX_COMPILER=clang++-20 -DLLVM_DIR=/usr/lib/llvm-20/cmake -DCMAKE_BUILD_TYPE=Release
          make -j2
          ctest --output-on-failure
      - store_test_results:
          path: test_results.xml
